config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users

  resources :users do
    collection do
      get :mine
    end
  end

  resources :articles do
    collection do
    end
  end

  get 'search' => 'search#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, :text, :category, presence: true
  validates :user, presence: true

  paginates_per 10

  CATEGORY = ['Art blog','Technology blog'].freeze

  def Article.all
    super.order(created_at: :desc)
  end

  def Article.current_articles current_page
    page current_page
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'application'
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :article_params, only: [:create]

  def new
    @article = current_user.article.new
  end

  def create
    @article = Article.new article_params
    @article.user = current_user
    if @article.save
      redirect_to mine_users_path
    else
      format.html { render :new }
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy!
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :category)
  end

  def set_article
    @article = Article.find params[:id]
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @articles = Article.where("title LIKE ?", "%#{params[:q]}%")
    if params[:category]
      @articles = @articles.where(category: params[:category])
    end

    if params[:user]
      @articles = @articles.where user_id: params[:user]
    end
    @articles = @articles.current_articles params[:page]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def mine
    if current_user
      @articles = current_user.article.current_articles params[:page]
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @articles = Article.current_articles params[:page]
    today = Time.new
    @today_updated_count = @articles.where("created_at >= ? and created_at <= ?", today.at_beginning_of_day, today.at_end_of_day).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<% editable ||= false %>
<div class="blog" id="<%= dom_id(article) %>">
  <h3><%= link_to article.title, article_path(article), class: "blog-title" %></h3>
  <ul class="list-inline">
    <li><span class="glyphicon glyphicon-time blog-info"></span><%= article.created_at.strftime '%Y-%m-%d' %></li>
    <li>
      <% unless editable %>
          <%= link_to search_path(user: article.user) do %>
              <span class="glyphicon glyphicon-user blog-info"></span><%= article.user.email %>
          <% end %>
      <% else %>
          <span class="glyphicon glyphicon-user blog-info"></span><%= article.user.email %>
      <% end %>
    </li>
  </ul>
  <p>
    <%= article.text.gsub(/<[^>]*>/, '').truncate(200) %>
  </p>
  <% if editable %>
      <div class="clearfix">
        <ul class="list-inline pull-right">
          <li><%= link_to "编辑", edit_article_path(article), class: "glyphicon glyphicon-time" %></li>
          <li><%= link_to "删除", article_path(article), method: :delete, data: {confirm: '确定要删除么？'}, remote: true, class: "btn btn-danger" %></li>
        </ul>
      </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= stylesheet_link_tag "article-form" %>
<%= javascript_include_tag "article-form" %>
<div class="container">
  <div class="articles-panel col-md-9">
    <ul class="breadcrumb">
      <li><%= link_to "Blog Demo", root_path %></li>
      <li><%= link_to "Mine", mine_users_path %></li>
    </ul>
    <%= simple_form_for(@article) do |f| %>
        <div class="info">
          <h5>主题标题
            <small class="pull-right">120</small>
          </h5>
        </div>
        <%= f.input :title, as: :string, label: false, placeholder: "请输入主题标题", input_html: {class: 'form-input form-control'} %>
        <div class="info">
          <h5>正文
            <small class="pull-right">20000</small>
          </h5>
        </div>
        <%= f.text_area :text, as: :text, label: false, class: 'form-area form-control wysihtml5', placeholder: '请输入正文', rows: 16 %>
        <div class="info form-bottom">
          <%= select_tag "article[category]", options_for_select(Article::CATEGORY, @article.category), class: "form-control category" %>
          <%= f.submit "发布", class: 'btn btn-primary pull-right' %>
        </div>
    <% end %>
  </div>
</div>

<script type="application/javascript">
  $('.wysihtml5').each(function(i, elem) {
    $(elem).wysihtml5({
      toolbar: {
        "color": true,
        "size": 'sm'
      },
      "locale" : 'zh-CN',
    });
  });
</script>

app/views/articles/destroy.js.erb
$("#<%= dom_id(@article) %>").remove();
$("#article-count").replaceWith("<%= current_user.article.count %>");

app/views/articles/edit.html.erb
<%= render "form" %>

app/views/articles/new.html.erb
<%= render "form" %>

app/views/articles/show.html.erb
<div class="container">
  <div class="article-panel col-md-9">
    <ul class="breadcrumb">
      <li><%= link_to "Blog Demo", root_path %></li>
      <li><%= link_to @article.category, mine_users_path %></li>
    </ul>
    <h2 class="article-title text-center"><%= @article.title %></h2>
    <div class="align-center divider-bottom">
      <ul class="list-inline">
        <li><span class="glyphicon glyphicon-time blog-info"></span><%= @article.created_at.strftime '%Y-%m-%d' %>
        </li>
        <li>
          <%= link_to user_path(@article.user) do %>
              <span class="glyphicon glyphicon-user blog-info"></span><%= @article.user.email %>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="article-content">
      <%= raw(@article.text) %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog Demo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
  <script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="nav navbar-default nav-bottom-border" role="navigation">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/">
        <%= image_tag "logo.png", class: "navbar-left logo" %>
        <span class="navbar-brand brand">Blog Demo</span>
      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Technology blog", search_path(category: "Technology blog") %></li>
        <li><%= link_to "Art blog", search_path(category: "Art blog") %></li>
        <li>
        <form class="navbar-form nav-search-form" action="/search" method="get" role="search">
          <div class="input-group nav-search-group">
            <input type="text" name="q" class="form-control" placeholder="search" value="<%= params[:q] %>">
            <span class="input-group-btn">
              <input type="submit" class="btn btn-primary" value="Search!">
            </span>
          </div>
        </form>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation">
                  <%= link_to mine_users_path do %>
                      <span class="glyphicon glyphicon-user"></span>
                      我的主页
                  <% end %>
                </li>
                <li role="presentation" class="divider"></li>
                <li role="presentation">
                  <%= link_to destroy_user_session_path, method: 'DELETE' do %>
                      <span class="glyphicon glyphicon-off"></span>
                      退出登录
                  <% end %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>
<%= image_tag "shadow_light.png", class: "nav-shadow" %>

<%= yield %>

<div class="footer">
  © 2016 Blog Demo
</div>
</body>
</html>

app/views/search/index.html.erb
<div class="container">
  <div class="content">
    <%= render partial: 'articles/article', collection: @articles %>
    <%= paginate @articles %>
  </div>
</div>

app/views/users/mine.html.erb
<div class="container">
  <h2>我发布的文章
    <small> 共有<span id="article-count"><%= current_user.article.count %></span>篇</small>
    <%= link_to "发布 Blog ", new_article_path, class: "btn btn-primary pull-right" %>
  </h2>

  <%=render partial: 'articles/article',collection: @articles,locals: {editable: true} %>

  <%= paginate @articles %>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <% if @today_updated_count > 0 %>
      <div class="alert alert-success alert-dismissible update-alert" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        今天已经更新<strong> <%= @today_updated_count %> </strong>篇文章
      </div>
  <% end %>
  <div class="content">
    <div class="col-md-9 content-panel">
      <%=render partial: 'articles/article',collection: @articles %>
      <%= paginate @articles %>
    </div>
    <div class="col-md-3">
      <h6 class="about-title">ABOUT ME</h6>
      <%= image_tag "blog_13-480x320.jpg", style: 'width:100%' %>
      <p class="about-info">
        关于我，中央提出，党的十八大代表应是共产党员中的优秀分子，在坚持先进性的同时应具有广泛的代...
      </p>
    </div>
  </div>
</div>